### ISSUE TITLE
Block Drops and Other Issues

### ISSUE THREAD

**Issue by BioMasterZap** [Immodernist/Endorium#4]
I've been trying v1.0.8 of the mod for Fabric 1.20.4 and noticed a few unexpected behaviors. Most of them involve block drops and some may have been intended, but here is a list of what I noticed.

- Tungsten Ore always mines for 1 Raw Tungsten, even when broken with Silk Touch or Fortune III.
- Incandescent Lamps do not seem to have an effective tool to break them, but will break if the block they are on is broken.
- Incandescent Lamps do not drop if broken, even with Silk Touch, but will drop if the block they are on is broken.
- Obsidian Decorated Glass does not drop if broken, even with Silk Touch.
- Ogana Grass and Ogana Burdock cannot be harvested with Silk Touch.
- End Moss requires a pickaxe to break, unlike normal Moss.
- End Moss does not spread like normal Moss with Bonemeal and Bonemeal on End Moss or Mossy End Stone cannot create more Ogana Grass and Ogana Burdock.
- Cracked End Stone Bricks does not have a recipe nor spawn that I have noticed.
- Endorium and Tungsten Blocks work as a Beacon Base, but Endorium and Tungsten Ingots do not work for Beacon Activations (though this also has a UI aspect so it may have been intentionally excluded).

Also, the Mysterious Relic Endorium Sword seems to intend to have no durability loss for breaking blocks, but even on blocks that a sword breaks quicker like Cobwebs, Bamboo, and Infested Stone, swords still lose 2 durability since they are not the "proper tool". This means that the Mysterious Relic Endorium Sword has the same durability loss (2) as a normal Endorium Sword and other Swords when breaking blocks while losing 3 durability when attacking entities while other swords only lose 1 durability on enemies. It still does offer 1 Attack Damage more than the normal Endorium Sword, but its relic effect does not provide any benefit, at least from the things I tested.

Aside from those few, mostly minor, issues everything else seemed to work fine, including the other Relic Tools. Lastly, while looking into the mod, I saw that on the Curseforge Forge version, the license is listed as Public Domain but on the Curseforge Fabric version and Modrinth it is marked as All Rights Reserved, which I bring up because I am thinking of including it in a Mod Pack and try to make sure that is within the licenses of the mods.

**Comment by Immodernist** [comment]
Thank you for appointing the issues and for the time testing it. 

Cracked End Stone Bricks do spawn alongside the shipwreck structure by small chance. The relic sword lower durability loss when breaking blocks is apparently not even implemented, missed perhaps when porting from 1.16, my fault, as well as appointing it as 100%, when in fact it is 50%. This issue and the loot table with block hardness will take for proper rechecking, and soon will include in the version. The Beacon activators are probably better to skip, for the reason to avoid misleading with the Beacon interface and due to the approximate rarity of the mod resources, it is not overly required. However bonemeal is intentionally does not work on End Moss, though it might be more vanilla way to add it then. The licencing is now changed to CC Zero on Modrinth, so there shoud be no problems including the mod in a pack.

**Comment by BioMasterZap** [comment]
I just saw and tested the new update and all the issues I brought up seem to be fixed. Though now that the Curious Hoe is +30% Block Speed, it might be overlapping more with the Mysterious Hoe (+20% Block Speed and -50% Entity Durability) than intended. But it is also kinda hard to tell speed differences with hoes so one might be more effective on certain blocks than the other. Anyway, thanks for the prompt reply and update.

**Comment by Immodernist** [comment]
The effect +30% is applied only to the intended blocks like leaves, while +20% is overall efficiency addition. But this might be changed to something like efficiency on ice blocks.
